describe('Flight search and booking UI tests', ()=>{
  before(() => {
    // Resets database before running each test
    cy.exec('python manage.py migrate --noinput')
    cy.exec('python manage.py loaddata TicketsApp/fixtures/test_data.json')
  });

  describe('No Filter Applied Search Flights', ()=>{
  it('Visits the index page of Flight Tickets App and tries to search flights without entering search criteria', ()=>{
    cy.visit('http://127.0.0.1:8000/index/')
    cy.get('button').contains('Search').click()
    cy.url().should('include', '/index/')
  })
})

describe('Search Flights with Applied Filter', ()=>{
  it('Visits the index page of Flight Tickets App and tries to search flights with entered search criteria', ()=>{
    cy.visit('http://127.0.0.1:8000/index/')
    cy.get('select[name="departure_country"]').select(8)
    cy.get('select[name="arrival_country"]').select(2)
    cy.get('input[name="num_passengers"]').type(1)
    cy.get('button').contains('Search').click()
    cy.url().should('include', '/index/')
    cy.contains('Available Flights')
  })
})

describe('Search Flights with Applied Filter and select a seat', ()=>{
  it('Visits the index page of Flight Tickets App and tries to search flights with entered search criteria, after which clicks "view seats" and finished the whole procedure of booking by entering passenger details', ()=>{
    cy.visit('http://127.0.0.1:8000/index/')
    cy.get('select[name="departure_country"]').select(8)
    cy.get('select[name="arrival_country"]').select(2)
    cy.get('input[name="num_passengers"]').type(1)
    cy.get('button').contains('Search').click()
    cy.url().should('include', '/index/')
    cy.contains('Available Flights')
    cy.contains('View Seats').click()
    cy.url().should('include', '/login/')
    cy.get('input[name="username"]').type('admin')
    cy.get('input[name="password"]').type('admin')
    cy.contains('Login').click()
    cy.url().should('include', '/flight_details/')
    cy.contains('B2').click()
    cy.contains('Confirm Selection').click()
    cy.get('input[name="form-0-first_name"]').type('John')
    cy.get('input[name="form-0-last_name"]').type('Doe')
    cy.get('input[name="form-0-passport_number"]').type('C123456')
    cy.get('select[name="form-0-country"]').select(8)
    cy.contains('Confirm').click()
    cy.url().should('include', '/booking_details/')
    cy.contains('John Doe')
  })
})

  describe('Search Flights with Applied Filter and try to select an already booked seat or more than the specified number of seats', ()=>{
  it('Visits the index page of Flight Tickets App and tries to search flights with enterd search criteria, after which clicks view seats, and tries to select a booked seat or more than the specified number of seats, afterwards user finished the procedure with correct steps', ()=>{
    cy.visit('http://127.0.0.1:8000/index/')
    cy.get('select[name="departure_country"]').select(8)
    cy.get('select[name="arrival_country"]').select(2)
    cy.get('input[name="num_passengers"]').type(2)
    cy.get('button').contains('Search').click()
    cy.url().should('include', '/index/')
    cy.contains('Available Flights')
    cy.contains('View Seats').click()
    cy.url().should('include', '/login/')
    cy.get('input[name="username"]').type('admin')
    cy.get('input[name="password"]').type('admin')
    cy.contains('Login').click()
    cy.url().should('include', '/flight_details/')
    cy.contains('B2').click()
    cy.contains('Confirm Selection').should('not.be.enabled')
    cy.url().should('include', '/flight_details/') //ensure user says on the same page
    cy.contains('C3').click()
    cy.contains('D4').click()
    cy.contains('Confirm Selection').click()
    cy.contains('Confirm').click()
    cy.url().should('include', '/enter_details/') //ensure user stays on the same page
    cy.get('input[name="form-0-first_name"]').type('Name2')
    cy.get('input[name="form-0-last_name"]').type('Surname2')
    cy.get('input[name="form-0-passport_number"]').type('C654321')
    cy.get('select[name="form-0-country"]').select(7)
    cy.get('input[name="form-1-first_name"]').type('Name3')
    cy.get('input[name="form-1-last_name"]').type('Surname3')
    cy.get('input[name="form-1-passport_number"]').type('C000000')
    cy.get('select[name="form-1-country"]').select(7)
    cy.contains('Confirm').click()
    cy.url().should('include', '/booking_details/')
    cy.contains('Name3')
    cy.contains('Name2')
  })
})

describe('Complete whole booking procedure, search again, logout, and try to see the booked flights', ()=>{
  it('Searches for flight, chooses a seat, and completes the booking procedure, goes to the search page again, logs out and tries to see the booked flights', ()=>{
    cy.visit('http://127.0.0.1:8000/index/')
    cy.get('select[name="departure_country"]').select(8)
    cy.get('select[name="arrival_country"]').select(2)
    cy.get('input[name="num_passengers"]').type(1)
    cy.get('button').contains('Search').click()
    cy.url().should('include', '/index/')
    cy.contains('Available Flights')
    cy.contains('View Seats').click()
    cy.url().should('include', '/login/')
    cy.get('input[name="username"]').type('admin')
    cy.get('input[name="password"]').type('admin')
    cy.contains('Login').click()
    cy.url().should('include', '/flight_details/')
    cy.contains('E5').click()
    cy.contains('Confirm Selection').should('be.enabled')
    cy.contains('Confirm Selection').click()
    cy.url().should('include', '/enter_details/') //ensure user stays on the same page
    cy.get('input[name="form-0-first_name"]').type('Name4')
    cy.get('input[name="form-0-last_name"]').type('Surname4')
    cy.get('input[name="form-0-passport_number"]').type('C010101')
    cy.get('select[name="form-0-country"]').select(3)
    cy.contains('Confirm').click()
    cy.url().should('include', '/booking_details/')
    cy.contains('Name4')
    cy.contains('C010101')
    cy.contains('Search Flights').click()
    cy.contains('Logout').click()
    cy.contains('My Tickets').click()
    cy.url().should('include', '/login/')
    cy.get('input[name="username"]').type('admin')
    cy.get('input[name="password"]').type('admin')
    cy.contains('Login').click()
    cy.contains('Name4')
    cy.contains('C010101')
  })
})

})
